import { describe, expect, it } from "vitest";
import { Direction, getNewState, LoadingSpan } from "./useSortedImageLoading";

describe("useSortedImageLoading", () => {
  describe("getNewState", () => {
    it.each([
      {
        description: "list starts at 0, round 1",
        batchSize: 1,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 0],
        loadedImageIndex: 0,
        initialImageIndex: 0,
        imageArrayLength: 9,
        expected: {
          newLoadingSpan: [0, 1],
          newLastDirection: "ascending",
          newBatchSize: 2,
        },
      },
      {
        ldescription: "list starts a 0, round 2",
        batchSize: 2,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 1],
        loadedImageIndex: 1,
        initialImageIndex: 0,
        imageArrayLength: 9,
        expected: {
          newLoadingSpan: [0, 3],
          newLastDirection: "ascending",
          newBatchSize: 3,
        },
      },
      {
        description: "list starts at 0, round 3",
        batchSize: 3,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 3],
        loadedImageIndex: 3,
        initialImageIndex: 0,
        imageArrayLength: 9,
        expected: {
          newLoadingSpan: [0, 6],
          newLastDirection: "ascending",
          newBatchSize: 4,
        },
      },
      {
        description: "list starts at 0, round 4",
        batchSize: 4,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 6],
        loadedImageIndex: 6,
        initialImageIndex: 0,
        imageArrayLength: 9,
        expected: {
          newLoadingSpan: [0, 10],
          newLastDirection: "ascending",
          newBatchSize: 5,
        },
      },
      {
        description: "list starts at 0 ends below batchSize, round 5",
        batchSize: 5,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 10],
        loadedImageIndex: 9,
        initialImageIndex: 0,
        imageArrayLength: 9,
        expected: {
          newLoadingSpan: [0, 15],
          newLastDirection: "ascending",
          newBatchSize: 6,
        },
      },
      {
        description: "list starts at 0, ends at BatchSize, round 5",
        batchSize: 5,
        lastDirection: "ascending",
        lastLoadingSpan: [0, 10],
        loadedImageIndex: 10,
        initialImageIndex: 0,
        imageArrayLength: 10,
        expected: {
          newLoadingSpan: [0, 15],
          newLastDirection: "ascending",
          newBatchSize: 6,
        },
      },
      {
        description: "list starts at 10, round 1",
        batchSize: 1,
        lastDirection: "ascending",
        lastLoadingSpan: [10, 10],
        loadedImageIndex: 10,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [10, 11],
          newLastDirection: "ascending",
          newBatchSize: 2,
        },
      },
      {
        description: "list starts at 10, round 2",
        batchSize: 2,
        lastDirection: "ascending",
        lastLoadingSpan: [10, 11],
        loadedImageIndex: 11,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [8, 11],
          newLastDirection: "descending",
          newBatchSize: null,
        },
      },
      {
        description: "list starts at 10, round 3",
        batchSize: 2,
        lastDirection: "descending",
        lastLoadingSpan: [8, 11],
        loadedImageIndex: 9,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [8, 13],
          newLastDirection: "ascending",
          newBatchSize: 3,
        },
      },
      {
        description: "list starts at 10, round 4",
        batchSize: 3,
        lastDirection: "ascending",
        lastLoadingSpan: [8, 13],
        loadedImageIndex: 13,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [5, 13],
          newLastDirection: "descending",
          newBatchSize: null,
        },
      },
      {
        description: "list starts at 10, round 5",
        batchSize: 3,
        lastDirection: "descending",
        lastLoadingSpan: [5, 13],
        loadedImageIndex: 7,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [5, 16],
          newLastDirection: "ascending",
          newBatchSize: 4,
        },
      },
      {
        description: "list starts at 10, round 6",
        batchSize: 4,
        lastDirection: "ascending",
        lastLoadingSpan: [5, 16],
        loadedImageIndex: 16,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [1, 16],
          newLastDirection: "descending",
          newBatchSize: null,
        },
      },
      {
        description: "list starts at 10, round 7",
        batchSize: 4,
        lastDirection: "descending",
        lastLoadingSpan: [1, 16],
        loadedImageIndex: 4,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [1, 20],
          newLastDirection: "ascending",
          newBatchSize: 5,
        },
      },
      {
        description: "list starts at 10, round 8",
        batchSize: 5,
        lastDirection: "ascending",
        lastLoadingSpan: [1, 20],
        loadedImageIndex: 20,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [-4, 20],
          newLastDirection: "descending",
          newBatchSize: null,
        },
      },
      {
        description: "list starts at 10, round 9",
        batchSize: 5,
        lastDirection: "descending",
        lastLoadingSpan: [-4, 20],
        loadedImageIndex: 0,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: {
          newLoadingSpan: [-4, 25],
          newLastDirection: "ascending",
          newBatchSize: 6,
        },
      },
      ,
      {
        description: "list starts at 10, round 9, index 1",
        batchSize: 5,
        lastDirection: "descending",
        lastLoadingSpan: [-4, 20],
        loadedImageIndex: 1,
        initialImageIndex: 10,
        imageArrayLength: 20,
        expected: undefined,
      },
    ])(
      "returns correct loadingSpan when $description",
      ({
        batchSize,
        lastDirection,
        lastLoadingSpan,
        loadedImageIndex,
        initialImageIndex,
        imageArrayLength,
        expected,
      }) => {
        const result = getNewState({
          batchSize,
          lastDirection: lastDirection as Direction,
          lastLoadingSpan: lastLoadingSpan as LoadingSpan,
          loadedImageIndex,
          initialImageIndex,
          imageArrayLength,
        });
        expect(result).toStrictEqual(expected);
      },
    );
  });
});
